from __future__ import annotations

from typing import Protocol


class CaptchaSolver(Protocol):
    async def verify_ready(self) -> bool: ...
    async def solve(self, expected_length: int | None = None) -> str: ...
    async def solve_image(self, image_bytes: bytes, expected_length: int | None = None) -> str: ...
    async def cancel_active_response(self) -> None: ...
