from __future__ import annotations

# Values captured from the Purchase eStamp article select in process.md.
# The live portal remains the source of truth and is checked again before submission.
ARTICLE_OPTIONS = (
    "Acknowledgement",
    "Administration Bond",
    "Adoption Deed",
    "Affidavit",
    "Agreement or Memorandum of an Agreement",
    "Agreement Relating to Deposit of Title Deeds,Pawn",
    "Appointment In Execution of a power",
    "Appraisement of valuation",
    "Apprenticeship Deed",
    "Articles of Association of a company",
    "Articles of Clerkship",
    "Award",
    "Bond",
    "Cancellation",
    "Certificate of Sale",
    "Charter Party",
    "Composition Deed",
    "Conveyance",
    "Copy or Extract",
    "Counter part or Duplicate",
    "Custom Bonds",
    "Debenture",
    "Deed of Exchange",
    "Divorce",
    "Entry as an advocate, on the roll of any High Court.",
    "Gift",
    "Indemnity Bond",
    "Instrument of Further Charge",
    "Lease",
    "Letter of Licence",
    "Memorandom of Association of a company",
    "Mortgage Deed",
    "Mortgage of a crop",
    "Notarial Act",
    "Note of Memorandum",
    "Note of Protest by Master of a Ship",
    "Partition",
    "Partnership",
    "Power of Attorney",
    "Protest of a Master of a Ship",
    "Protest of Bill or Note",
    "Reconveyance of Mortgaged Property",
    "Release Deed",
    "Respodentia Bond",
    "Security Bond",
    "Settlement Deed",
    "Share Warrants",
    "Surrender of Lease",
    "Transfer",
    "Transfer of Lease",
    "Trust",
)
